version: "3.8"
services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo-data:/data/db

    mongo-express:
        container_name: mymongoexpress
        image: mongo-express
        restart: always
        depends_on:
            - mongo  # Ensure MongoDB starts first
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_BASICAUTH: false  
            ME_CONFIG_MONGODB_AUTH_DATABASE: admin
        ports:
            - "8081:8081"
            
    backend:
        build: ./backend
        container_name: backend
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        environment:
            MONGO_URI: "mongodb://admin:password@mongo:27017/userdb?authSource=admin"


    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        ports:
            - "5173:5173"
        depends_on:
            - backend

volumes:
    mongo-data:
        driver: local
